---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yunxi.
--- DateTime: 2019/12/25 15:45
--- 取消恢复脚本
---

-- 抢购编号和类型标识
local activityId = KEYS[1];
-- 三个Key变量
local useripKey = KEYS[2];
local useridKey = KEYS[3];
local orderIdKey = KEYS[4];

-- userIP和userId
local userip = ARGV[1];
local userid = ARGV[2];

-- 抢购数量
local balanceNum = "bn";

-- 活动状态
local activityState = "st";

-- 抢购数量
local purchaseNum = tonumber(ARGV[3]);
-- 限购标识 1:非抢购商品，2:为抢购
local activityType = tonumber(ARGV[4]);
-- 抢购订单编号
local orderIdValue = ARGV[5];

-- 非限购类型归还资格后返回成功
if activityType == 1 then
    redis.call('HDEL', useripKey, userip);
    redis.call('HDEL', useridKey, userid);
    return -100;
end

-- 判断是否存在抢购活动，0为不存在
if 0 == redis.call('EXISTS', activityId) then
    return -907;
end

-- 判断是否存在订单Id
local orderNum = redis.call('HGET', orderIdKey, orderIdValue);
if orderNum == false then
    return -2003;
end

-- 订单余额为0直接返回成功
if tonumber(orderNum) == 0 then
    return -100;
end

-- 判断原订单数量和取消数量是否一致，如果不一致返回错误
if tonumber(orderNum) ~= purchaseNum then
    return -2004;
end

-- 删除限购记录
redis.call('HDEL', useripKey, userip);
redis.call('HDEL', useridKey, userid);

-- 订单金额反向操作
redis.call('HINCRBY', orderIdKey, orderIdValue, -purchaseNum);

-- 还原剩余商品数量
redis.call('HINCRBY', activityId, balanceNum, purchaseNum);

-- 状态恢复
if "0" == redis.call('HGET', activityId, activityState) then
    redis.call('HSET', activityId, activityState, "1");
end

return -100;